version: 2
jobs:
    build:
        machine: true
        working_directory: ~/repo
        steps:
            - checkout
            - run: ./build.sh
            - run: docker-compose up -d
            - run: ./test.sh
